name = "thrift-ls"
version = "0.0.3"
author = "joyme123"
display-name = "thrift-ls"
description = "thrift language server"
wasm = "bin/lapce-thrift.wasm"
icon = "icon.png"
repository = "https://github.com/joyme123/lapce-thrift"

[activation]
language = ["thrift"]
workspace-contains = ["**/*.thrift"]

[config."lsp.serverPath"]
default = "/usr/local/bin/thriftls"
description = "Path to custom LSP executable"

# [config."lsp.serverArgs"]
# default = []
# description = ""

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
